/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

public class App {

    public static void main(String[] args) {
        WeldContainer container = new Weld()
            .disableDiscovery()
            .addBeanClass(Entry.class)
            .addBeanClass(Dog.class)
            .initialize();

        container.select(Entry.class).get().perform();
        container.shutdown();
    }

    @ApplicationScoped
    private static class Entry {
        private final Dog dog;

        @Inject
        public Entry(Dog dog) {
            this.dog = dog;
        }

        public void perform() {
            dog.bark();
        }
    }

    @ApplicationScoped
    public static class Dog {
        public void bark() {
            System.out.println("Woff");
        }
    }

}
