/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.core.http.HttpServerResponse;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import org.jboss.resteasy.plugins.server.vertx.VertxResteasyDeployment;
import org.jboss.weld.environment.se.Weld;
import org.jboss.weld.environment.se.WeldContainer;

public class App {

    public static void main(String[] args) {
        WeldContainer container = new Weld()
            .disableDiscovery()
            .initialize();

//        container.select(Entry.class).get().perform();
        container.shutdown();

        VertxResteasyDeployment deployment = new VertxResteasyDeployment();
        deployment.getRegistry().addPerInstanceResource(Resource.class);
    }

    public class Resource {
        @GET
        @Path("/somepath")
//        @Produces("text/plain")
        public String context(
            @Context Context context,
            @Context Vertx vertx,
            @Context HttpServerRequest req,
            @Context HttpServerResponse resp
        ) {
            return "the-response";
        }
    }
}
