[versions]
lombok = "1.18.36"
weld = "6.0.0.Final"
vertx = "4.5.12"
junit-jupiter = "5.11.1"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
weld = { module = "org.jboss.weld.se:weld-se-shaded", version.ref = "weld" }
vertx = { module = "io.vertx:vertx-core", version.ref = "vertx" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
