/*
 * This source file was generated by the Gradle 'init' task
 */
package dk.codella.nucleo;

import dk.codella.demo.Demo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

@Disabled
class AppTest {
    @Test void appHasAGreeting() {

    }
}
