/*
 * This source file was generated by the Gradle 'init' task
 */
package dk.codella.nucleo;

import dk.codella.demo.Demo;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Demo classUnderTest = new Demo();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
